### ISSUE TITLE
Is it possible to combine SparseConvNet with PointNet?

### ISSUE THREAD

**Issue by zenroad** [btgraham/SparseConvNet#11]
Thank you for your  work! I am studying 3d semantic segmentation. Since SparseConvNet is so useful.Is it possible to combine SparseConvNet with PointNet?

**Comment by btgraham** [comment]
I guess so. For example, you could use small PointNets to capture subvoxel information, then accumulate the latent representation for each non-empty voxel using SparseConvNet.

**Comment by zenroad** [comment]
thank you~
