### ISSUE TITLE
how about Using linear regression?

### ISSUE THREAD

**Issue by tengshaofeng** [btgraham/SparseConvNet#8]
hi, btgrahma.
    I am so appreciated with your great work. But, i am a little confused with the following sentence in your paper:
"Using linear regression on just the CNN generated probability distributions, without any of the meta-data, also seems to work well."

linear regression is done based features  probability distributions?
for example, you have 3 nets and repeat random transformation 3 times, in addition left-right eye, so you have 3*3*2*5=90 dimension of features for linear regression？

**Comment by btgraham** [comment]
Re: the Diabetic Retinopathy competition
The 5 probabilities produced by softmax add to 1, so there are only 4 degrees of freedom (drop one of the outputs). If you have multiple networks, you can just average them. Using both the eye being tested, and the other eye, that gives 4+4=8 features. You can then use linear regression to approximate the class.

**Comment by tengshaofeng** [comment]
to left eye ,for example the output average of three nets is (0.1, 0.1,  0.1, 0.1, 0.6), then drop which one? 
to right eye ,for exaple (0.1, 0.1,  0.1, 0.05, 0.65),
so do you say that the 8 features are (0.1, 0.1,  0.1, 0.1,  0.1, 0.1,  0.1, 0.05 )?
I can not understand.

**Comment by btgraham** [comment]
Say the probabilities are (L[0],L[1],L[2],L[3],L[4]) for the left eye and (R[0],R[1],R[2],R[3],R[4]) for the right eye. Use (L[1],L[2],L[3],L[4],R[1],R[2],R[3],R[4]) to predict the left eye and 
(R[1],R[2],R[3],R[4],L[1],L[2],L[3],L[4]) to predict the right eye.

**Comment by tengshaofeng** [comment]
thanks for your reply。
three questions
1）why drop the L(0)？  
2） linear regress with features(L[1],L[2],L[3],L[4],R[1],R[2],R[3],R[4]) with labels rates.    
used the trained model to map a float value. and set the threshold to decide which rate?
for example <0.5  map to 0
3) have you tried just average of output of multi nets and repeat random tests? how much is kappa score?

**Comment by tengshaofeng** [comment]
and the fourth question is:
  after you  preprocess the image.  the value is around 128.
![image](https://cloud.githubusercontent.com/assets/9246739/26627031/9bcf777c-462b-11e7-8f88-f48f80bc23ef.png)

and whether needed normalization?
like (x-mean)/std or x/255.0?

**Comment by btgraham** [comment]
1) L(0) adds no extra information (linearly dependent)
2) Use cross validation to decide the thresholds.
3) Similar to using forests.
4) Only the corners should look like that. The center should be more interesting.

**Comment by tengshaofeng** [comment]
thank you very much for your help.  It really helped me.
but to  the fourth question I am not confused about the 128 around the corner.
I am confused about that if I should do normalization such as (img-mean)/std   before input to the cnn net

**Comment by btgraham** [comment]
I think I scaled to [-1, +1], but other scalings could work.

**Comment by tengshaofeng** [comment]
ok, thank you very much. so kind of you .

**Comment by tengshaofeng** [comment]
@btgraham 
sorry to bother you again. i am reading your paper .
![image](https://cloud.githubusercontent.com/assets/9246739/26721781/c0f4a6a4-47bf-11e7-904a-fa6148d2f07c.png)
I know the radius is the eye's.  but i do not know the exact size of input image. is it  540*540?

**Comment by btgraham** [comment]
Input size should be >= 540x540. Larger sizes were used to allow data augmentation (translations).

**Comment by tengshaofeng** [comment]
for example, image of 540*540 is randomly cropped from image of  600*600. then take the image of 540*540 to the input?
